---
title: "Visualising and Analysing Time-series Financial Data"
description: |
  In this artile, I will reveal the impact of COVID-19 on the stock prices of top 40 companies in Singapore by market capitalisation.
author:
  - name: Min Xiaoqi 
    url: https://www.linkedin.com/in/xiaoqi-min/
    affiliation: Master of IT in Business, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/master-it-business/financial-technology-and-analytics-track
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages = c('tidyquant','rmarkdown','tidyverse','readr','ggHoriPlot', 'ggthemes')
for (p in packages) {
  if(!require(p,character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

import the data consisting symbols 
```{r}
stocks_symbol <- read_csv("data/companiesmarketcap.com - Largest companies in Singapore by market capitalization.csv")
```

delete the unnecessary columns 
```{r}
stocks_symbol = subset(stocks_symbol, select = -c(Rank,marketcap, `price (USD)`, country) )
```

select only top 40 rows
```{r}
stocks_list <- stocks_symbol[1:40,]
```

Defining an empty dataframe
Defining a for loop with iterations equal to the no of rows we want to append.
Using rbind() to append the output of one iteration to the dataframe
```{r}
stocks = data.frame()
from_date = "2020-01-01"
to_date = "2021-12-31"
period_type = "days" 
for (i in stocks_list) {
  stock_selected <-  i 
  stock_data_daily <-  tq_get(stock_selected,
                            get = "stock.prices",
                            from = from_date,
                            to = to_date) %>% tq_transmute(select = NULL,
                                                         mutate_fun = to.period,
                                                         period  = period_type)
  stocks = rbind(stocks, stock_data_daily)
}

```

```{r}
get_stocks <- tq_get(stocks_list$Symbol,
                     get = "stock.prices",
                     from = "2020-01-01",
                     to = "2021-12-31")
              tq_transmute(stocks_list$Symbol,
                           select = NULL, 
                           mutate_fun = to.period, 
                           period = "weeks") 
```

```{r}
Stock40_weekly <- stocks_list$Symbol %>%
  tq_get(get = "stock.prices", from = "2020-01-01", to = "2021-12-31") %>%
  group_by(Symbol) %>%
  tq_transmute(select     = NULL, 
               mutate_fun = to.period, 
               period  = "weeks") 
```
